add wave /T_ALU_TEST/CLOCK
add wave /T_ALU_TEST/OP
add wave /T_ALU_TEST/REG_A
add wave /T_ALU_TEST/REG_B
add wave /T_ALU_TEST/REG_D
add wave /T_ALU_TEST/CST
add wave /T_ALU_TEST/FLAG_O
add wave /T_ALU_TEST/FLAG_U
add wave /T_ALU_TEST/FLAG_Z
add wave /T_ALU_TEST/FLAG_T
add wave /T_ALU_TEST/FLAG_C
add wave /T_ALU_TEST/FLAG_L
add wave /T_ALU_TEST/FLAG_E
add wave /T_ALU_TEST/FLAG_G
